SELECT  misth_ypal.surname ,
           misth_ypal.name ,
           misth_ypal.fathername ,
           misth_ypal.mitroo ,
           misth_ypal.adt ,
           misth_ypal.afm ,
           misth_ypal.doy ,
           misth_ypal.bankno ,
           misth_ypal.bank ,
           misth_ypal.childs ,
           misth_ypal.prostmeli ,
           misth_ypal.klimakio ,
           misth_ypal.bathmos ,
           misth_ypal.klados ,
           misth_ypal.birthdate ,
           misth_ypal.hireddate ,
           misth_zpoikog.descoikog ,
           misth_zpidikot.descidikot ,
           misth_zpthesi.descthesi ,
           misth_zptmima.desctmima ,
           misth_final.kodfinal ,
			  misth_final.aa,
           misth_final.descfinal ,
           misth_final.datefinal ,
			  misth_final.title,
           misth_final_ypal.kodypal ,
           misth_zptamio.desctamio  
        FROM misth_ypal LEFT OUTER JOIN misth_zpoikog ON misth_ypal.kodoikog = misth_zpoikog.kodoikog AND misth_ypal.kodxrisi = misth_zpoikog.kodxrisi LEFT OUTER JOIN misth_zpidikot ON misth_ypal.kodidikot = misth_zpidikot.kodidikot AND misth_ypal.kodxrisi = misth_zpidikot.kodxrisi LEFT OUTER JOIN misth_zpthesi ON misth_ypal.kodthesi = misth_zpthesi.kodthesi AND misth_ypal.kodxrisi = misth_zpthesi.kodxrisi LEFT OUTER JOIN misth_zptmima ON misth_ypal.kodtmima = misth_zptmima.kodtmima AND misth_ypal.kodxrisi = misth_zptmima.kodxrisi LEFT OUTER JOIN misth_zptamio ON misth_ypal.kodtamio = misth_zptamio.kodtamio AND misth_ypal.kodxrisi = misth_zptamio.kodxrisi ,
           misth_final_ypal ,
           misth_final    
        WHERE ( misth_final_ypal.kodfinal = misth_final.kodfinal ) and          ( misth_final_ypal.kodxrisi = misth_final.kodxrisi ) and          ( misth_final_ypal.kodypal = misth_ypal.kodypal ) and          ( misth_final_ypal.kodxrisi = misth_ypal.kodxrisi ) and          ( ( misth_final_ypal.kodfinal = :arg_kodfinal ) and          ( misth_final_ypal.kodxrisi = :arg_kodxrisi ) ) 
        ORDER BY misth_ypal.surname          ASC,
           misth_ypal.name          ASC,
           misth_ypal.fathername          ASC  